apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sLatestImage
metadata:
  name: k8slatestimage
spec:
  enforcementAction: deny
  match:
    excludedNamespaces: ["gatekeeper-system", "argocd"]
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    message: "WHY DID YOU TRY!!"
