apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8slatestimage
spec:
  crd:
    spec:
      names:
        kind: K8sLatestImage
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            message:
              type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8slatestimage

        violation[{"msg": msg}] {
          container := input.review.object.spec.containers[_]
          not startswith(container.image, "repo.example.com/")
          msg := sprintf("Image %v for container %v does not come from repo.example.org/", [container.image, container.name])
        }



