apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8slatestimage
spec:
  crd:
    spec:
      names:
        kind: K8sLatestImage
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            message:
              type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8slatestimage

        violation[{"msg": msg}] {
          message := input.parameters.message
          1 > 0
          msg := sprintf("POD-CREATION-DENIED: %v", [message])
        }

#        violation[{"msg": msg}] {
#          container := input.review.object.spec.containers[_]
#          not endswith(container.image, ":latest")
#          msg := sprintf("container %v", [container.name])
#        }



