apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: appsetconstraint
spec:
  crd:
    spec:
      names:
        kind: AppSetConstraint
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package appsetconstraint

        violation[{"msg": msg}] {
          name := input.review.object.metadata.name
          not endswith(name, "-appset")
          msg := sprintf("Name should end with '-appset'. Name: <%v>", [name])
        }

        violation[{"msg": msg}] {
          name := input.review.object.metadata.name
          generator := input.review.object.spec.generators[_]
          not generator.matrix
          msg := sprintf("generator <%v> uses non-matrix generator", [name])
        }

        violation[{"msg": msg}] {
          namespace := input.review.object.metadata.namespace
          not namespace = "argocd"
          msg := sprintf("Using Namespace <%v>. Should be 'argocd'", [namespace])
        }


