apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AppSetConstraint
metadata:
  name: denyappset
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["argoproj.io"]
        kinds: ["ApplicationSet", "appset","appsets","ApplicationSets", "applicationsets"]
