apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: deploy-deleter
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - delete
