apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- blue-secret-manager-rolebinding.yaml
- blue-secret-manager.yaml
- red-secret-manager-role.yaml
- red-secret-manager-rolebinding.yaml
