apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: secret-manager
  namespace: red
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
